name: build

on:
    workflow_dispatch:
    pull_request:
    push:

jobs:
  build:
    if: github.repository == 'mikepqr/resume.md'
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Install package
      run: uv tool install .

    - name: Initialize resume templates
      run: resume-markdown init

    - name: Make resume
      run: resume-markdown --debug build

    - name: Rename output (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
          mv resume.pdf resume_${{ runner.os }}.pdf
          mv resume.html resume_${{ runner.os }}.html

    - name: Rename output (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
          Move-Item resume.pdf resume_Windows.pdf
          Move-Item resume.html resume_Windows.html

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
          name: resume-${{ runner.os }}
          path: |
              *.pdf
              *.html
